export const policyData = {
  terms: {
    title: 'Terms & Conditions',
    intro: 'These terms apply to vendors and drivers operating under the UseDrive platform.',
    items: [
      'Vendors and drivers work together as UseDrive partners.',
      'Vendor responsibility is to take care of the complete trip start-to-end billing process in the partner app. If any default from the vendor leaves a trip incomplete, penalty charges apply. Continued defaults may lead to termination from UseDrive cabs.',
      'Vendor responsibility is to add the car and driver to assign the current booking. If any default occurs, penalties apply and continued default may lead to termination.',
      'Billing amounts shown in the application are the vendor’s responsibility to collect in cash. If a customer complains and the driver collects extra amount, penalty charges apply to the vendor.',
      'Vendor accept cancellations must follow the cancellation policy.',
      'The company can terminate the vendor at any time if they cross any policy or fail to meet responsibilities.',
      'Vendors must ensure all driver and vehicle documents are active. If a vendor sends inactive documents, the vehicle vendor may face FIR action.',
      'If the vendor or driver misbehaves on a trip, or if the customer uses the emergency panic button, support must be contacted immediately and the trip should end. The customer should pay 0/- and the vendor should handle the payment process.',
      'If the vendor or support line behaves badly, uses unprofessional language, or mistreats customers, the vendor can be terminated immediately.',
      'All vendors must accept UseDrive Cabs team terms and conditions agreement before activating their account.',
      'Vendors must follow the driver and cab at least 15 minutes before pickup to ensure the pickup is on time. If the cab is late or does not show, mark it as cancelled and penalties up to ₹1500/- will be applied to the vendor.',
      'If the driver waits more than 1 hour at pickup and the customer does not respond or cancels, vendors can report to customer support. ₹500/- will be added to the vendor wallet as cancellation fees from the customer wallet.',
      'Trip fares may change at any time based on seasons before booking.',
      'The driver is responsible for collecting the cash from the customer as shown in the application. UseDrive is not responsible for any pending customer amount.',
      'Toll, permit, and parking are the driver’s responsibility to collect from the customer if not included in the application.',
      'Making the customer a personal trip for future use may lead to termination.',
      'Unprofessional driver behavior leads to termination.',
      'Customer complaints against the driver or car lead to penalty charges, and continued complaints lead to termination.',
      'Cancellation of bookings is penalized based on timing, with charges from ₹500/- to ₹1500/-.',
      'Starting kilometer and closing kilometer will be calculated from the client location.',
      'Minimum one-way drop is 130 km for all vehicles.',
      'Round trip minimum is 250 km per day.',
      'Changing driver or vehicle for the booking carries penalty charges and continued violations lead to termination.',
      'Deposit amount will not be returned for terminated drivers or vehicles.',
      'Commission submission must be made 4-5 hours before completing the booking; delay may lead to blocking.',
    ],
  },
  cancellation: {
    title: 'Cancellation Policy',
    intro: 'Cancellation penalties are calculated from the booking time and apply to the vendor or driver as described.',
    list: [
      { label: '0 to 30 mins', amount: '₹500/-' },
      { label: '0 to 60 mins', amount: '₹600/-' },
      { label: '0 to 120 mins', amount: '₹800/-' },
      { label: '0 to 180 mins', amount: '₹1000/-' },
      { label: '0 to 240 mins', amount: '₹1500/-' },
    ],
  },
};
